version: '{build} (about to be changed)'
image: Visual Studio 2017
environment:
  NUGET_API_KEY:
    secure: eEi8gt5ne+a+N5fYINa2DqF7DCqOzYCE5udL5XzZm2qhcaMJkg9Tg4d0QObF9s3L
init:
  - git config --global core.autocrlf true
dotnet_csproj:
  patch: true
  file: 'src\**\*.csproj'
  version: $(PACKAGE_VERSION)
  package_version: $(PACKAGE_VERSION)
install:
  - choco install gitversion.portable -y -pre
  - git fetch --tags
  - ps: |
      ./get-version.ps1
      Update-AppveyorBuild -Version $buildVersion
      $env:PACKAGE_VERSION = $packageVersion
before_build:
  - dotnet --version
  - dotnet restore src --verbosity m
build_script:
  - dotnet pack src -c Release
test:
  assemblies:
    only:
      - '**\*.Tests.dll'
artifacts:
  - path: src/**/*.nupkg
deploy:
  - provider: GitHub
    artifact: /src\/.*\.nupkg/
    draft: false
    prerelease: false
    auth_token:
      secure: +hGjnoxWXiKJf2SOZhYHq2NgoU9h7dUSGEe40GtjdinfD82rOvnGmsC/PSdc4AwA
    on:
      appveyor_repo_tag: true
deploy_script:
  - ps: ./deploy-nugets.ps1
