version: 0.0.0-{build}+{commitId}
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
  - git fetch -t
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
install:
  - ps: |
      Update-AppveyorBuild -Version "$(git describe | % { $_.TrimStart('v') })+$env:APPVEYOR_BUILD_NUMBER"
      if ($LastExitCode -ne 0) { $host.SetShouldExit($LastExitCode)  }
before_build:
  - dotnet --version
  - dotnet restore src --verbosity m
build_script:
  - dotnet pack src -c Release
artifacts:
  - path: src/**/*.nupkg
    name: Nuget Packages
    type: NuGetPackage
clone_depth: 1
deploy:
  - provider: GitHub
    artifact: /.*\.nupkg/
    draft: false
    prerelease: false
    on:
      appveyor_repo_tag: true
  - provider: NuGet
    api_key:
      secure: eEi8gt5ne+a+N5fYINa2DqF7DCqOzYCE5udL5XzZm2qhcaMJkg9Tg4d0QObF9s3L
    skip_symbols: false
    artifact: /dist\/.*\.nupkg/